### ISSUE TITLE
# prof.h:280: PROF error (Permission denied) - Aborted (core dumped)

### ISSUE THREAD

**Issue by schoettl** [cyrus-and/prof#1]
Hi, your library looks very nice and simple to use.

But do you have an idea, why your minimal example does not work at my system?

```c
#include "prof.h"

int main()
{
    PROF_START();
    // slow code goes here...
    PROF_STDOUT();
}
```

```
$ gcc test.c
$ ./a.out
# prof.h:280: PROF error (Permission denied)
Aborted (core dumped)
```

Thanks, Jakob

**Comment by cyrus-and** [comment]
Thanks!

You might need to tune `perf_event_paranoid` ([source][1]):

```
perf_event_paranoid:

Controls use of the performance events system by unprivileged
users (without CAP_SYS_ADMIN).  The default value is 2.

 -1: Allow use of (almost) all events by all users
     Ignore mlock limit after perf_event_mlock_kb without CAP_IPC_LOCK
>=0: Disallow ftrace function tracepoint by users without CAP_SYS_ADMIN
     Disallow raw tracepoint access by users without CAP_SYS_ADMIN
>=1: Disallow CPU event access by users without CAP_SYS_ADMIN
>=2: Disallow kernel profiling by users without CAP_SYS_ADMIN
```

For example with:

```console
$ echo -1 | sudo tee /proc/sys/kernel/perf_event_paranoid
```

You can make it permanent with:

```console
$ echo 'kernel.perf_event_paranoid=-1' | sudo tee /etc/sysctl.d/local.conf
```

Use the most appropriate value for your use case instead of -1.

[1]: https://www.kernel.org/doc/Documentation/sysctl/kernel.txt

**Comment by schoettl** [comment]
> You might need to tune `perf_event_paranoid` ([source](https://www.kernel.org/doc/Documentation/sysctl/kernel.txt)):

Thanks! That's it. Calling my program with `sudo` also works, but I prefer your suggestion.

Maybe you want to add this information to the your well-written README.

**Comment by cyrus-and** [comment]
> Maybe you want to add this information to the your well-written README.

Good idea, the value of that setting changed in Linux 4.6 so now it's an important thing to know.
