### ISSUE TITLE
Does not work with multi-threaded programs

### ISSUE THREAD

**Issue by VishalSubramanyam** [cyrus-and/prof#2]
Steps to reproduce:

1. Include "prof.h" as set up the macros as needed
2. Spawn a new thread while your main threads waits for the new thread to join it and perform PROF_START and PROF_DO inside that thread

Current behavior: Counters are always zero
Expected behavior: perf counters actual values?

My threads are pinned to a fixed core, so mixing up counters from different cores isn't a concern for me.

Initialization of prof.h might be happening during program initialization before the thread is spawned, so initialization and PROF_START/DO are on different threads, this might be a concern?

**Comment by cyrus-and** [comment]
Providing a minimal example would make my work easier...

**Comment by cyrus-and** [comment]
Added support for multi-threaded programs, see the [README](https://github.com/cyrus-and/prof#installation). Please let me know if something's not working as expected, and thanks for the heads up.
